### ISSUE TITLE
Lack of software licensing information

### ISSUE THREAD

**Issue by alessio** [regen-network/cosmos-proto#5]
Hi,

This repository lacks information regarding the license under whose terms the software is being distributed.
Could you add a LICENSE/COPYING file to clarify the licensing, please?

Thanks for considering.

**Comment by aaronc** [comment]
Sorry about that! Done.

By the way, repository will be deprecated once https://github.com/cosmos/cosmos-sdk/issues/8270 is done and we will no longer need the `replace` directive in the cosmos-sdk g.mod.
